baseURL = "http://adjusted-r.netlify.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Adjusted-R"
theme = "desktop/bdown/themes/hugo-dream-plus"
themesDir = "../../"   #Don't use this, only for netlify
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "adjusted-r"
googleAnalytics = "UA-120070920-1"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Mohammad Alfaifi"
	description = "Data science with R and Python"
	avatar = "/img/myavatar.jpg"
	motto = ""
	enableToc = true
	enableShareCard = true

	favicon = ""
  	
  	#Background settings
	enableColorBG= false
	bgBlur = "0px"
	bgImage = "/img/bk.jpeg"
  
	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 6

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	twitter = "alfaifi_moh" 
	github = "mohammad-alfaifi"
	linkedin = "mohammadalfaifi"
	siteStartYear = 2018