baseurl = "http://moh.netlify.com/"
title = "Data Science with R and Python"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Mohammad Alfaifi"
    description = "JData Science with R and Python"
    keywords = "data science, R, Python, Time Series, Machine Learning"
    info = ""

    hideCredits = true
    hideCopyright = true

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/mohammad-alfaifi"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/alfaifi_moh"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/mohammadalfaifi/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
