baseURL = "http://adjusted-r.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Data Science with R and Python"
theme = "hugo-dream-plus"
themesDir = "../../"   #Don't use this, only for netlify

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "disqus_Z7ozFSnuFz"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Mohammad Alfaifi"
	description = "Data Science with R and Python "
	avatar = "/static/images/myavatar.jpg"
	motto = ""
	enableToc = true
	enableShareCard = true

	favicon = ""
  	
  	#Background settings
	enableColorBG= false
	bgBlur = "0px"
	bgImage = "static/images/bk.jpeg"
  
	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 6

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = ""
	github = "mohammadalfaifi"
	stackoverflow = ""
	medium = ""
	twitter = "alfaifi_moh" 
	siteStartYear = 2018