name = "After Dark"
license = "WTFPL"
licenselink = "https://github.com/comfusion/after-dark/blob/master/COPYING"
description = "Data Science with R and Python"
homepage = "https://adjusted-r.com"
min_version = 0.27

[author]
  name = "Mohammad Alfaifi"
  homepage = "adjusted-r.com"
